// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/homework_operate_type.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 作业操作类型
type HomeworkOperateType int32

const (
	// 保存
	HomeworkOperateType_OPERATE_SAVE HomeworkOperateType = 0
	// 提交
	HomeworkOperateType_OPERATE_SUBMITTED HomeworkOperateType = 1
	// 纠正
	HomeworkOperateType_OPERATE_RECTIFY HomeworkOperateType = 2
)

// Enum value maps for HomeworkOperateType.
var (
	HomeworkOperateType_name = map[int32]string{
		0: "OPERATE_SAVE",
		1: "OPERATE_SUBMITTED",
		2: "OPERATE_RECTIFY",
	}
	HomeworkOperateType_value = map[string]int32{
		"OPERATE_SAVE":      0,
		"OPERATE_SUBMITTED": 1,
		"OPERATE_RECTIFY":   2,
	}
)

func (x HomeworkOperateType) Enum() *HomeworkOperateType {
	p := new(HomeworkOperateType)
	*p = x
	return p
}

func (x HomeworkOperateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HomeworkOperateType) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_homework_operate_type_proto_enumTypes[0].Descriptor()
}

func (HomeworkOperateType) Type() protoreflect.EnumType {
	return &file_relo_core_homework_operate_type_proto_enumTypes[0]
}

func (x HomeworkOperateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HomeworkOperateType.Descriptor instead.
func (HomeworkOperateType) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_homework_operate_type_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_homework_operate_type_proto protoreflect.FileDescriptor

var file_relo_core_homework_operate_type_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2a, 0x53, 0x0a, 0x13, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x50, 0x45,
	0x52, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4f,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x43, 0x54, 0x49, 0x46, 0x59, 0x10, 0x02, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_homework_operate_type_proto_rawDescOnce sync.Once
	file_relo_core_homework_operate_type_proto_rawDescData = file_relo_core_homework_operate_type_proto_rawDesc
)

func file_relo_core_homework_operate_type_proto_rawDescGZIP() []byte {
	file_relo_core_homework_operate_type_proto_rawDescOnce.Do(func() {
		file_relo_core_homework_operate_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_homework_operate_type_proto_rawDescData)
	})
	return file_relo_core_homework_operate_type_proto_rawDescData
}

var file_relo_core_homework_operate_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_homework_operate_type_proto_goTypes = []interface{}{
	(HomeworkOperateType)(0), // 0: relo.core.HomeworkOperateType
}
var file_relo_core_homework_operate_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_homework_operate_type_proto_init() }
func file_relo_core_homework_operate_type_proto_init() {
	if File_relo_core_homework_operate_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_homework_operate_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_homework_operate_type_proto_goTypes,
		DependencyIndexes: file_relo_core_homework_operate_type_proto_depIdxs,
		EnumInfos:         file_relo_core_homework_operate_type_proto_enumTypes,
	}.Build()
	File_relo_core_homework_operate_type_proto = out.File
	file_relo_core_homework_operate_type_proto_rawDesc = nil
	file_relo_core_homework_operate_type_proto_goTypes = nil
	file_relo_core_homework_operate_type_proto_depIdxs = nil
}
