// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/homework_submitted_state.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 作业提交状态
type HomeworkSubmittedState int32

const (
	// 尚未提交
	HomeworkSubmittedState_NOT HomeworkSubmittedState = 0
	// 已经提交
	HomeworkSubmittedState_ALREADY HomeworkSubmittedState = 1
	// 保存
	HomeworkSubmittedState_SAVE HomeworkSubmittedState = 2
)

// Enum value maps for HomeworkSubmittedState.
var (
	HomeworkSubmittedState_name = map[int32]string{
		0: "NOT",
		1: "ALREADY",
		2: "SAVE",
	}
	HomeworkSubmittedState_value = map[string]int32{
		"NOT":     0,
		"ALREADY": 1,
		"SAVE":    2,
	}
)

func (x HomeworkSubmittedState) Enum() *HomeworkSubmittedState {
	p := new(HomeworkSubmittedState)
	*p = x
	return p
}

func (x HomeworkSubmittedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HomeworkSubmittedState) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_homework_submitted_state_proto_enumTypes[0].Descriptor()
}

func (HomeworkSubmittedState) Type() protoreflect.EnumType {
	return &file_relo_core_homework_submitted_state_proto_enumTypes[0]
}

func (x HomeworkSubmittedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HomeworkSubmittedState.Descriptor instead.
func (HomeworkSubmittedState) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_homework_submitted_state_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_homework_submitted_state_proto protoreflect.FileDescriptor

var file_relo_core_homework_submitted_state_proto_rawDesc = []byte{
	0x0a, 0x28, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6c, 0x6f,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0x38, 0x0a, 0x16, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4c, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41, 0x56, 0x45, 0x10, 0x02, 0x42,
	0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65,
	0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_homework_submitted_state_proto_rawDescOnce sync.Once
	file_relo_core_homework_submitted_state_proto_rawDescData = file_relo_core_homework_submitted_state_proto_rawDesc
)

func file_relo_core_homework_submitted_state_proto_rawDescGZIP() []byte {
	file_relo_core_homework_submitted_state_proto_rawDescOnce.Do(func() {
		file_relo_core_homework_submitted_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_homework_submitted_state_proto_rawDescData)
	})
	return file_relo_core_homework_submitted_state_proto_rawDescData
}

var file_relo_core_homework_submitted_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_homework_submitted_state_proto_goTypes = []interface{}{
	(HomeworkSubmittedState)(0), // 0: relo.core.HomeworkSubmittedState
}
var file_relo_core_homework_submitted_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_homework_submitted_state_proto_init() }
func file_relo_core_homework_submitted_state_proto_init() {
	if File_relo_core_homework_submitted_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_homework_submitted_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_homework_submitted_state_proto_goTypes,
		DependencyIndexes: file_relo_core_homework_submitted_state_proto_depIdxs,
		EnumInfos:         file_relo_core_homework_submitted_state_proto_enumTypes,
	}.Build()
	File_relo_core_homework_submitted_state_proto = out.File
	file_relo_core_homework_submitted_state_proto_rawDesc = nil
	file_relo_core_homework_submitted_state_proto_goTypes = nil
	file_relo_core_homework_submitted_state_proto_depIdxs = nil
}
