// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/cloudfile/completed_status.proto

package cloudfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件上传状态
type CompletedStatus int32

const (
	// 未完成
	CompletedStatus_NO CompletedStatus = 0
	// 已完成
	CompletedStatus_YES CompletedStatus = 1
)

// Enum value maps for CompletedStatus.
var (
	CompletedStatus_name = map[int32]string{
		0: "NO",
		1: "YES",
	}
	CompletedStatus_value = map[string]int32{
		"NO":  0,
		"YES": 1,
	}
)

func (x CompletedStatus) Enum() *CompletedStatus {
	p := new(CompletedStatus)
	*p = x
	return p
}

func (x CompletedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompletedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_cloudfile_completed_status_proto_enumTypes[0].Descriptor()
}

func (CompletedStatus) Type() protoreflect.EnumType {
	return &file_relo_core_cloudfile_completed_status_proto_enumTypes[0]
}

func (x CompletedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompletedStatus.Descriptor instead.
func (CompletedStatus) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_cloudfile_completed_status_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_cloudfile_completed_status_proto protoreflect.FileDescriptor

var file_relo_core_cloudfile_completed_status_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75,
	0x64, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x65,
	0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c,
	0x65, 0x2a, 0x22, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x59, 0x45, 0x53, 0x10, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_cloudfile_completed_status_proto_rawDescOnce sync.Once
	file_relo_core_cloudfile_completed_status_proto_rawDescData = file_relo_core_cloudfile_completed_status_proto_rawDesc
)

func file_relo_core_cloudfile_completed_status_proto_rawDescGZIP() []byte {
	file_relo_core_cloudfile_completed_status_proto_rawDescOnce.Do(func() {
		file_relo_core_cloudfile_completed_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_cloudfile_completed_status_proto_rawDescData)
	})
	return file_relo_core_cloudfile_completed_status_proto_rawDescData
}

var file_relo_core_cloudfile_completed_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_cloudfile_completed_status_proto_goTypes = []interface{}{
	(CompletedStatus)(0), // 0: relo.core.cloudfile.CompletedStatus
}
var file_relo_core_cloudfile_completed_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_cloudfile_completed_status_proto_init() }
func file_relo_core_cloudfile_completed_status_proto_init() {
	if File_relo_core_cloudfile_completed_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_cloudfile_completed_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_cloudfile_completed_status_proto_goTypes,
		DependencyIndexes: file_relo_core_cloudfile_completed_status_proto_depIdxs,
		EnumInfos:         file_relo_core_cloudfile_completed_status_proto_enumTypes,
	}.Build()
	File_relo_core_cloudfile_completed_status_proto = out.File
	file_relo_core_cloudfile_completed_status_proto_rawDesc = nil
	file_relo_core_cloudfile_completed_status_proto_goTypes = nil
	file_relo_core_cloudfile_completed_status_proto_depIdxs = nil
}
