// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/schedule/repeat_type.proto

package schedule

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 重复类型
type RepeatType int32

const (
	// 0 不重复
	RepeatType_NONE RepeatType = 0
	// 1 按年
	RepeatType_YEAR RepeatType = 1
	// 2 按月
	RepeatType_MONTH RepeatType = 2
	// 3 按日
	RepeatType_DAY RepeatType = 3
	// 4 按周
	RepeatType_WEEK RepeatType = 4
)

// Enum value maps for RepeatType.
var (
	RepeatType_name = map[int32]string{
		0: "NONE",
		1: "YEAR",
		2: "MONTH",
		3: "DAY",
		4: "WEEK",
	}
	RepeatType_value = map[string]int32{
		"NONE":  0,
		"YEAR":  1,
		"MONTH": 2,
		"DAY":   3,
		"WEEK":  4,
	}
)

func (x RepeatType) Enum() *RepeatType {
	p := new(RepeatType)
	*p = x
	return p
}

func (x RepeatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatType) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_schedule_repeat_type_proto_enumTypes[0].Descriptor()
}

func (RepeatType) Type() protoreflect.EnumType {
	return &file_relo_core_schedule_repeat_type_proto_enumTypes[0]
}

func (x RepeatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatType.Descriptor instead.
func (RepeatType) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_schedule_repeat_type_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_schedule_repeat_type_proto protoreflect.FileDescriptor

var file_relo_core_schedule_repeat_type_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x2f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2a, 0x3e, 0x0a, 0x0a, 0x52, 0x65,
	0x70, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x59, 0x45, 0x41, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x41, 0x59, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x45, 0x4b, 0x10, 0x04, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_schedule_repeat_type_proto_rawDescOnce sync.Once
	file_relo_core_schedule_repeat_type_proto_rawDescData = file_relo_core_schedule_repeat_type_proto_rawDesc
)

func file_relo_core_schedule_repeat_type_proto_rawDescGZIP() []byte {
	file_relo_core_schedule_repeat_type_proto_rawDescOnce.Do(func() {
		file_relo_core_schedule_repeat_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_schedule_repeat_type_proto_rawDescData)
	})
	return file_relo_core_schedule_repeat_type_proto_rawDescData
}

var file_relo_core_schedule_repeat_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_schedule_repeat_type_proto_goTypes = []interface{}{
	(RepeatType)(0), // 0: relo.core.schedule.RepeatType
}
var file_relo_core_schedule_repeat_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_schedule_repeat_type_proto_init() }
func file_relo_core_schedule_repeat_type_proto_init() {
	if File_relo_core_schedule_repeat_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_schedule_repeat_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_schedule_repeat_type_proto_goTypes,
		DependencyIndexes: file_relo_core_schedule_repeat_type_proto_depIdxs,
		EnumInfos:         file_relo_core_schedule_repeat_type_proto_enumTypes,
	}.Build()
	File_relo_core_schedule_repeat_type_proto = out.File
	file_relo_core_schedule_repeat_type_proto_rawDesc = nil
	file_relo_core_schedule_repeat_type_proto_goTypes = nil
	file_relo_core_schedule_repeat_type_proto_depIdxs = nil
}
