// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/meeting/whiteboard_mqtt.proto

package meeting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 白板服Mqtt
type WhiteboardMqtt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 服务器列表
	// @gotags: json:"urls,omitempty"
	Urls []string `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	// 用户名
	// @gotags: json:"username,omitempty"
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// 格式化
	// @gotags: json:"formatter,omitempty"
	Formatter *MqttFormatter `protobuf:"bytes,4,opt,name=formatter,proto3" json:"formatter,omitempty"`
	// 客户端编号，限制只能满足特定格式，方便后续功能开发，比如:踢下线、统计
	// @gotags: json:"clientId"
	ClientId string `protobuf:"bytes,5,opt,name=clientId,proto3" json:"clientId"`
}

func (x *WhiteboardMqtt) Reset() {
	*x = WhiteboardMqtt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_meeting_whiteboard_mqtt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhiteboardMqtt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhiteboardMqtt) ProtoMessage() {}

func (x *WhiteboardMqtt) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_meeting_whiteboard_mqtt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhiteboardMqtt.ProtoReflect.Descriptor instead.
func (*WhiteboardMqtt) Descriptor() ([]byte, []int) {
	return file_relo_core_meeting_whiteboard_mqtt_proto_rawDescGZIP(), []int{0}
}

func (x *WhiteboardMqtt) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *WhiteboardMqtt) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WhiteboardMqtt) GetFormatter() *MqttFormatter {
	if x != nil {
		return x.Formatter
	}
	return nil
}

func (x *WhiteboardMqtt) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

var File_relo_core_meeting_whiteboard_mqtt_proto protoreflect.FileDescriptor

var file_relo_core_meeting_whiteboard_mqtt_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x2f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x6d,
	0x71, 0x74, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x72, 0x65, 0x6c, 0x6f, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x26, 0x72, 0x65,
	0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x6d, 0x71, 0x74, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x4d, 0x71, 0x74, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4d,
	0x71, 0x74, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x52, 0x09, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_meeting_whiteboard_mqtt_proto_rawDescOnce sync.Once
	file_relo_core_meeting_whiteboard_mqtt_proto_rawDescData = file_relo_core_meeting_whiteboard_mqtt_proto_rawDesc
)

func file_relo_core_meeting_whiteboard_mqtt_proto_rawDescGZIP() []byte {
	file_relo_core_meeting_whiteboard_mqtt_proto_rawDescOnce.Do(func() {
		file_relo_core_meeting_whiteboard_mqtt_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_meeting_whiteboard_mqtt_proto_rawDescData)
	})
	return file_relo_core_meeting_whiteboard_mqtt_proto_rawDescData
}

var file_relo_core_meeting_whiteboard_mqtt_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relo_core_meeting_whiteboard_mqtt_proto_goTypes = []interface{}{
	(*WhiteboardMqtt)(nil), // 0: relo.core.meeting.WhiteboardMqtt
	(*MqttFormatter)(nil),  // 1: relo.core.meeting.MqttFormatter
}
var file_relo_core_meeting_whiteboard_mqtt_proto_depIdxs = []int32{
	1, // 0: relo.core.meeting.WhiteboardMqtt.formatter:type_name -> relo.core.meeting.MqttFormatter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relo_core_meeting_whiteboard_mqtt_proto_init() }
func file_relo_core_meeting_whiteboard_mqtt_proto_init() {
	if File_relo_core_meeting_whiteboard_mqtt_proto != nil {
		return
	}
	file_relo_core_meeting_mqtt_formatter_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_relo_core_meeting_whiteboard_mqtt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhiteboardMqtt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_meeting_whiteboard_mqtt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_meeting_whiteboard_mqtt_proto_goTypes,
		DependencyIndexes: file_relo_core_meeting_whiteboard_mqtt_proto_depIdxs,
		MessageInfos:      file_relo_core_meeting_whiteboard_mqtt_proto_msgTypes,
	}.Build()
	File_relo_core_meeting_whiteboard_mqtt_proto = out.File
	file_relo_core_meeting_whiteboard_mqtt_proto_rawDesc = nil
	file_relo_core_meeting_whiteboard_mqtt_proto_goTypes = nil
	file_relo_core_meeting_whiteboard_mqtt_proto_depIdxs = nil
}
