// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/trtc/privelege_type.proto

package trtc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//  - 第 1 位：0000 0001 = 1，创建房间的权限
//  - 第 2 位：0000 0010 = 2，加入房间的权限
//  - 第 3 位：0000 0100 = 4，发送语音的权限
//  - 第 4 位：0000 1000 = 8，接收语音的权限
//  - 第 5 位：0001 0000 = 16，发送视频的权限
//  - 第 6 位：0010 0000 = 32，接收视频的权限
//  - 第 7 位：0100 0000 = 64，发送辅路（也就是屏幕分享）视频的权限
//  - 第 8 位：1000 0000 = 200，接收辅路（也就是屏幕分享）视频的权限
//  - privilegeMap == 1111 1111 == 255 代表该 userid 在该 roomid 房间内的所有功能权限。
//  - privilegeMap == 0010 1010 == 42  代表该 userid 拥有加入房间和接收音视频数据的权限，但不具备其他权限。
type PrivilegeType int32

const (
	// 未知
	PrivilegeType_UNSPECIFIED PrivilegeType = 0
	// 所有功能权限
	PrivilegeType_T255 PrivilegeType = 255
	// 加入房间和接收音视频数据的权限
	PrivilegeType_T43 PrivilegeType = 43
)

// Enum value maps for PrivilegeType.
var (
	PrivilegeType_name = map[int32]string{
		0:   "UNSPECIFIED",
		255: "T255",
		43:  "T43",
	}
	PrivilegeType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"T255":        255,
		"T43":         43,
	}
)

func (x PrivilegeType) Enum() *PrivilegeType {
	p := new(PrivilegeType)
	*p = x
	return p
}

func (x PrivilegeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivilegeType) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_trtc_privelege_type_proto_enumTypes[0].Descriptor()
}

func (PrivilegeType) Type() protoreflect.EnumType {
	return &file_relo_core_trtc_privelege_type_proto_enumTypes[0]
}

func (x PrivilegeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivilegeType.Descriptor instead.
func (PrivilegeType) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_trtc_privelege_type_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_trtc_privelege_type_proto protoreflect.FileDescriptor

var file_relo_core_trtc_privelege_type_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x74, 0x63,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x65, 0x6c, 0x65, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x74, 0x72, 0x74, 0x63, 0x2a, 0x34, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x04, 0x54, 0x32, 0x35, 0x35, 0x10,
	0xff, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x34, 0x33, 0x10, 0x2b, 0x42, 0x20, 0x5a, 0x1e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x74, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_trtc_privelege_type_proto_rawDescOnce sync.Once
	file_relo_core_trtc_privelege_type_proto_rawDescData = file_relo_core_trtc_privelege_type_proto_rawDesc
)

func file_relo_core_trtc_privelege_type_proto_rawDescGZIP() []byte {
	file_relo_core_trtc_privelege_type_proto_rawDescOnce.Do(func() {
		file_relo_core_trtc_privelege_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_trtc_privelege_type_proto_rawDescData)
	})
	return file_relo_core_trtc_privelege_type_proto_rawDescData
}

var file_relo_core_trtc_privelege_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_trtc_privelege_type_proto_goTypes = []interface{}{
	(PrivilegeType)(0), // 0: relo.core.trtc.PrivilegeType
}
var file_relo_core_trtc_privelege_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_trtc_privelege_type_proto_init() }
func file_relo_core_trtc_privelege_type_proto_init() {
	if File_relo_core_trtc_privelege_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_trtc_privelege_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_trtc_privelege_type_proto_goTypes,
		DependencyIndexes: file_relo_core_trtc_privelege_type_proto_depIdxs,
		EnumInfos:         file_relo_core_trtc_privelege_type_proto_enumTypes,
	}.Build()
	File_relo_core_trtc_privelege_type_proto = out.File
	file_relo_core_trtc_privelege_type_proto_rawDesc = nil
	file_relo_core_trtc_privelege_type_proto_goTypes = nil
	file_relo_core_trtc_privelege_type_proto_depIdxs = nil
}
