// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/record/start.proto

package record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 腾讯云录制信息数据
type StartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 请求操作类型,开始录制为Start
	// @gotags: json:"Action" validate:"required"
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"Action" validate:"required"`
	// 请求协议参数
	// @gotags: json:"Data" validate:"required"
	Data *Data `protobuf:"bytes,3,opt,name=data,proto3" json:"Data" validate:"required"`
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_record_start_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_record_start_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_relo_core_record_start_proto_rawDescGZIP(), []int{0}
}

func (x *StartReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StartReq) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 开始录制相关参数
type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 需要录制的WEB⻚⾯访问URL
	// @gotags: json:"RecordURL" validate:"required"
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"RecordURL" validate:"required"`
	// 录制画⾯宽度， 默认为1280， 合法取值范围[0, 2560]
	// @gotags: json:"Width"
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"Width"`
	// 录制画⾯⾼度， 默认为720， 合法取值范围[0, 2560]
	// @gotags: json:"Height"
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"Height"`
	// 录制结果通知回调地址
	// @gotags: json:"CallbackURL"
	CallbackUrl string `protobuf:"bytes,5,opt,name=callbackUrl,proto3" json:"CallbackURL"`
	// 录制最⼤时⻓限制， 单位s, 合法取值范围[0, 36000], 默认36000s(10⼩时)
	// @gotags: json:"MaxDurationLimit"
	MaxDuration int32 `protobuf:"varint,6,opt,name=maxDuration,proto3" json:"MaxDurationLimit"`
	// 开始录制输出参数
	// @gotags: json:"Output"
	Out *Out `protobuf:"bytes,7,opt,name=out,proto3" json:"Output"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_record_start_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_record_start_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_relo_core_record_start_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Data) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Data) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Data) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Data) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *Data) GetOut() *Out {
	if x != nil {
		return x.Out
	}
	return nil
}

// 录制输出参数
type Out struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 云存储参数
	// @gotags: json:"Cos"
	Cos *Cos `protobuf:"bytes,2,opt,name=cos,proto3" json:"Cos"`
}

func (x *Out) Reset() {
	*x = Out{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_record_start_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Out) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Out) ProtoMessage() {}

func (x *Out) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_record_start_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Out.ProtoReflect.Descriptor instead.
func (*Out) Descriptor() ([]byte, []int) {
	return file_relo_core_record_start_proto_rawDescGZIP(), []int{2}
}

func (x *Out) GetCos() *Cos {
	if x != nil {
		return x.Cos
	}
	return nil
}

// 腾讯云对象存储
type Cos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 录制文件回放域名，不设置为默认源站域名
	// @gotags: json:"Domain"
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"Domain"`
	// 录制文件存放空间，不设置默认为创建函数时设置的存储空间
	// @gotags: json:"Bucket"
	Bucket string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"Bucket"`
	// 录制文件存放区域，默认为存储空间所在区域
	// @gotags: json:"Region"
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"Region"`
	// 录制文件存放路径，不设置默认为 taskid
	// @gotags: json:"TargetDir"
	TargetDir string `protobuf:"bytes,5,opt,name=targetDir,proto3" json:"TargetDir"`
	// 录制文件名称，不设置为结束时间戳
	// @gotags: json:"TargetName"
	TargetName string `protobuf:"bytes,6,opt,name=targetName,proto3" json:"TargetName"`
}

func (x *Cos) Reset() {
	*x = Cos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_record_start_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cos) ProtoMessage() {}

func (x *Cos) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_record_start_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cos.ProtoReflect.Descriptor instead.
func (*Cos) Descriptor() ([]byte, []int) {
	return file_relo_core_record_start_proto_rawDescGZIP(), []int{3}
}

func (x *Cos) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cos) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Cos) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Cos) GetTargetDir() string {
	if x != nil {
		return x.TargetDir
	}
	return ""
}

func (x *Cos) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

// 录制基本响应信息
type StartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 错误类型，只有请求出错的时候才会返回此字段
	// @gotags: json:"ErrorCode"
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"ErrorCode"`
	// 错误说明，只有请求出错的时候才会返回此字段
	// @gotags: json:"ErrorMessage"
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"ErrorMessage"`
	// 请求ID
	// @gotags: json:"RequestID"
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"RequestID"`
	// 录制任务ID，只有开始录制成功的时候才会返回此字段
	// @gotags: json:"TaskID"
	TaskId string `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"TaskID"`
}

func (x *StartRsp) Reset() {
	*x = StartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relo_core_record_start_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRsp) ProtoMessage() {}

func (x *StartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relo_core_record_start_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRsp.ProtoReflect.Descriptor instead.
func (*StartRsp) Descriptor() ([]byte, []int) {
	return file_relo_core_record_start_proto_rawDescGZIP(), []int{4}
}

func (x *StartRsp) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StartRsp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartRsp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StartRsp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_relo_core_record_start_proto protoreflect.FileDescriptor

var file_relo_core_record_start_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0x4e, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xb3, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6d,
	0x61, 0x78, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x6d, 0x61, 0x78, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x03, 0x6f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4f, 0x75,
	0x74, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x22, 0x2e, 0x0a, 0x03, 0x4f, 0x75, 0x74, 0x12, 0x27, 0x0a,
	0x03, 0x63, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x6c,
	0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x43, 0x6f,
	0x73, 0x52, 0x03, 0x63, 0x6f, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x03, 0x43, 0x6f, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x44, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x44, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x42, 0x22, 0x5a,
	0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_record_start_proto_rawDescOnce sync.Once
	file_relo_core_record_start_proto_rawDescData = file_relo_core_record_start_proto_rawDesc
)

func file_relo_core_record_start_proto_rawDescGZIP() []byte {
	file_relo_core_record_start_proto_rawDescOnce.Do(func() {
		file_relo_core_record_start_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_record_start_proto_rawDescData)
	})
	return file_relo_core_record_start_proto_rawDescData
}

var file_relo_core_record_start_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relo_core_record_start_proto_goTypes = []interface{}{
	(*StartReq)(nil), // 0: relo.core.record.StartReq
	(*Data)(nil),     // 1: relo.core.record.Data
	(*Out)(nil),      // 2: relo.core.record.Out
	(*Cos)(nil),      // 3: relo.core.record.Cos
	(*StartRsp)(nil), // 4: relo.core.record.StartRsp
}
var file_relo_core_record_start_proto_depIdxs = []int32{
	1, // 0: relo.core.record.StartReq.data:type_name -> relo.core.record.Data
	2, // 1: relo.core.record.Data.out:type_name -> relo.core.record.Out
	3, // 2: relo.core.record.Out.cos:type_name -> relo.core.record.Cos
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_relo_core_record_start_proto_init() }
func file_relo_core_record_start_proto_init() {
	if File_relo_core_record_start_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relo_core_record_start_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_core_record_start_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_core_record_start_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Out); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_core_record_start_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relo_core_record_start_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_record_start_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_record_start_proto_goTypes,
		DependencyIndexes: file_relo_core_record_start_proto_depIdxs,
		MessageInfos:      file_relo_core_record_start_proto_msgTypes,
	}.Build()
	File_relo_core_record_start_proto = out.File
	file_relo_core_record_start_proto_rawDesc = nil
	file_relo_core_record_start_proto_goTypes = nil
	file_relo_core_record_start_proto_depIdxs = nil
}
