// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/meeting/video/type.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 视频类型
type Video int32

const (
	Video_AUDIO    Video = 0
	Video_P360     Video = 1
	Video_P480     Video = 2
	Video_P720     Video = 3
	Video_P1080    Video = 4
	Video_ORIGINAL Video = 5
)

// Enum value maps for Video.
var (
	Video_name = map[int32]string{
		0: "AUDIO",
		1: "P360",
		2: "P480",
		3: "P720",
		4: "P1080",
		5: "ORIGINAL",
	}
	Video_value = map[string]int32{
		"AUDIO":    0,
		"P360":     1,
		"P480":     2,
		"P720":     3,
		"P1080":    4,
		"ORIGINAL": 5,
	}
)

func (x Video) Enum() *Video {
	p := new(Video)
	*p = x
	return p
}

func (x Video) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Video) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_meeting_video_type_proto_enumTypes[0].Descriptor()
}

func (Video) Type() protoreflect.EnumType {
	return &file_relo_core_meeting_video_type_proto_enumTypes[0]
}

func (x Video) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Video.Descriptor instead.
func (Video) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_meeting_video_type_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_meeting_video_type_proto protoreflect.FileDescriptor

var file_relo_core_meeting_video_type_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2a, 0x49, 0x0a,
	0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x33, 0x36, 0x30, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x34, 0x38, 0x30, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x37, 0x32, 0x30, 0x10, 0x03, 0x12,
	0x09, 0x0a, 0x05, 0x50, 0x31, 0x30, 0x38, 0x30, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x52,
	0x49, 0x47, 0x49, 0x4e, 0x41, 0x4c, 0x10, 0x05, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_meeting_video_type_proto_rawDescOnce sync.Once
	file_relo_core_meeting_video_type_proto_rawDescData = file_relo_core_meeting_video_type_proto_rawDesc
)

func file_relo_core_meeting_video_type_proto_rawDescGZIP() []byte {
	file_relo_core_meeting_video_type_proto_rawDescOnce.Do(func() {
		file_relo_core_meeting_video_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_meeting_video_type_proto_rawDescData)
	})
	return file_relo_core_meeting_video_type_proto_rawDescData
}

var file_relo_core_meeting_video_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_meeting_video_type_proto_goTypes = []interface{}{
	(Video)(0), // 0: relo.core.meeting.video.Video
}
var file_relo_core_meeting_video_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_meeting_video_type_proto_init() }
func file_relo_core_meeting_video_type_proto_init() {
	if File_relo_core_meeting_video_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_meeting_video_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_meeting_video_type_proto_goTypes,
		DependencyIndexes: file_relo_core_meeting_video_type_proto_depIdxs,
		EnumInfos:         file_relo_core_meeting_video_type_proto_enumTypes,
	}.Build()
	File_relo_core_meeting_video_type_proto = out.File
	file_relo_core_meeting_video_type_proto_rawDesc = nil
	file_relo_core_meeting_video_type_proto_goTypes = nil
	file_relo_core_meeting_video_type_proto_depIdxs = nil
}
