// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: relo/core/course/material_type.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 课程教学资料类型
type MaterialType int32

const (
	// 未知
	MaterialType_MATERIAL_TYPE_UNSPECIFIED MaterialType = 0
	// 教学资料
	MaterialType_RESOURCE MaterialType = 1
	// 教案
	MaterialType_PLAN MaterialType = 2
)

// Enum value maps for MaterialType.
var (
	MaterialType_name = map[int32]string{
		0: "MATERIAL_TYPE_UNSPECIFIED",
		1: "RESOURCE",
		2: "PLAN",
	}
	MaterialType_value = map[string]int32{
		"MATERIAL_TYPE_UNSPECIFIED": 0,
		"RESOURCE":                  1,
		"PLAN":                      2,
	}
)

func (x MaterialType) Enum() *MaterialType {
	p := new(MaterialType)
	*p = x
	return p
}

func (x MaterialType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaterialType) Descriptor() protoreflect.EnumDescriptor {
	return file_relo_core_course_material_type_proto_enumTypes[0].Descriptor()
}

func (MaterialType) Type() protoreflect.EnumType {
	return &file_relo_core_course_material_type_proto_enumTypes[0]
}

func (x MaterialType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaterialType.Descriptor instead.
func (MaterialType) EnumDescriptor() ([]byte, []int) {
	return file_relo_core_course_material_type_proto_rawDescGZIP(), []int{0}
}

var File_relo_core_course_material_type_proto protoreflect.FileDescriptor

var file_relo_core_course_material_type_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x65, 0x6c, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x2f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x6c, 0x6f, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2a, 0x45, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x41, 0x54, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x4c, 0x41, 0x4e, 0x10, 0x02, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relo_core_course_material_type_proto_rawDescOnce sync.Once
	file_relo_core_course_material_type_proto_rawDescData = file_relo_core_course_material_type_proto_rawDesc
)

func file_relo_core_course_material_type_proto_rawDescGZIP() []byte {
	file_relo_core_course_material_type_proto_rawDescOnce.Do(func() {
		file_relo_core_course_material_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_relo_core_course_material_type_proto_rawDescData)
	})
	return file_relo_core_course_material_type_proto_rawDescData
}

var file_relo_core_course_material_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relo_core_course_material_type_proto_goTypes = []interface{}{
	(MaterialType)(0), // 0: relo.core.MaterialType
}
var file_relo_core_course_material_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relo_core_course_material_type_proto_init() }
func file_relo_core_course_material_type_proto_init() {
	if File_relo_core_course_material_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relo_core_course_material_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relo_core_course_material_type_proto_goTypes,
		DependencyIndexes: file_relo_core_course_material_type_proto_depIdxs,
		EnumInfos:         file_relo_core_course_material_type_proto_enumTypes,
	}.Build()
	File_relo_core_course_material_type_proto = out.File
	file_relo_core_course_material_type_proto_rawDesc = nil
	file_relo_core_course_material_type_proto_goTypes = nil
	file_relo_core_course_material_type_proto_depIdxs = nil
}
